### PR TITLE
Add otter.ai

### PR DESCRIPTION
**Pull request by derekcwhite**
Otter has three paid plans: Pro, Business, Enterprise
Enterprise pricing is not listed, but the only difference between Business and Enterprise is SSO and it requires a minimum of 100 users.

### CODE REVIEW

**Comment by daallgeier** [comment]
Have you had a conversation with the sales team there? 

At the moment I'd not approve it.  May need to add a footnote for them explaining the 100 user minimum purchase?

**Comment by doransmestad** [comment]
I agree with @daallgeier.  I think we use $20 as the base as that is the first non-personal license offered according to the pricing plan.  Given your comment @derekcwhite  I assume they charge $20/user at the enterprise plan?

Makes the tax calculation is a bit tricky though as the tax could be $0 or $1900 depending on user count.  :thinking:   I'll open a discussion topic.

**Comment by derekcwhite** [comment]
You are both right, I completely missed that Pro was an individual plan. Thanks for keeping me honest! I am closing this PR.

**Comment by daallgeier** [comment]
I mean adding them still seems like something we should do. The question is just a "how?".

**Pull request closed without merging**
